# Generated by Django 3.2.8 on 2021-10-22 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='certificado',
            field=models.FileField(upload_to=''),
        ),
    ]
